### ISSUE TITLE
Adding IE 10 and IE 11 support for CSS animations

### ISSUE THREAD

**Issue by smykes** [heyman/leaflet-usermarker#2]
If you add the following rules to the CSS file you will have IE 10 and IE 11 support for the CSS animations.  Unfortunately some of us have to support these browsers.

``` css
@keyframes leaflet-usermarker-pulsate {
    from {
        transform: scale(0.5);
        opacity: 1.0;
    }
    95% {
        transform: scale(1.3);
        opacity: 0;
    }
    to {
        transform: scale(0.7);
        opacity: 0;
    }
}
```

``` css
.leaflet-usermarker i.pulse,
.leaflet-usermarker-small i.pulse {
    display: block;

    -moz-animation: leaflet-usermarker-pulsate 1.5s ease-in-out infinite;
    -webkit-animation: leaflet-usermarker-pulsate 1.5s ease-in-out infinite;
    animation: leaflet-usermarker-pulsate 1.5s ease-in-out infinite;
    border:1pt solid #fff;
    /* make a circle */
    -moz-border-radius:51px;
    -webkit-border-radius:51px;
    border-radius:51px;
    /* multiply the shadows, inside and outside the circle */
    -moz-box-shadow:inset 0 0 5px #06f, inset 0 0 5px #06f, inset 0 0 5px #06f, 0 0 5px #06f, 0 0 5px #06f, 0 0 5px #06f;
    -webkit-box-shadow:inset 0 0 5px #06f, inset 0 0 5px #06f, inset 0 0 5px #06f, 0 0 5px #06f, 0 0 5px #06f, 0 0 5px #06f;
    box-shadow:inset 0 0 5px #06f, inset 0 0 5px #06f, inset 0 0 5px #06f, 0 0 5px #06f, 0 0 5px #06f, 0 0 5px #06f;
    /* set the ring's new dimension and re-center it */
    height:61px!important;
    margin:-14px 0 0 -14px;
    width:61px!important;
}
```
